### ISSUE TITLE
Critical Error - Forum Down - Please help!!!

### ISSUE THREAD

**Issue by AlgoryThmOriginal** [AlexSheer/phpbb3.1-Stopforumspam#4]
Forum Version: Phpbb v3.2.5
Forum Language: English
Issue description: I installed the latest version and I got the message below. I uninstalled completely, reinstalled and same message again and forum down. Please help me in order to fix it! Thank you!

Fatal error: Uncaught phpbb\language\exception\language_file_not_found: Language file ./../ext/sheer/stopforumspam/language/en/stopforumspam.php couldn't be opened. in /nvtronics.org/main/phpbb/language/language_file_loader.php:185 Stack trace: #0 /nvtronics.org/main/phpbb/language/language_file_loader.php(143): phpbb\language\language_file_loader->get_language_file_path('./../ext/sheer/...', 'stopforumspam.p...', Array) #1 /nvtronics.org/main/phpbb/language/language_file_loader.php(103): phpbb\language\language_file_loader->load_file('./../ext/sheer/...', 'stopforumspam', Array, Array) #2 /nvtronics.org/main/phpbb/language/language.php(643): phpbb\language\language_file_loader->load_extension('sheer/stopforum...', 'stopforumspam', Array, Array) #3 /nvtronics.org/main/phpbb/language/language.php(180): phpbb\language\language->load_extension('sheer/stopforum...', 'stopforumspam') #4 /nvtronics.org/main/phpbb/user.php(540): phpbb\language\la in /nvtronics.org/main/phpbb/language/language_file_loader.php on line 185

**Comment by AlexSheer** [comment]
Fixed! https://github.com/AlexSheer/phpbb3.2-Stopforumspam/commit/934b82fe3441d4a975779fe1601ad7b8954740d3

**Comment by AlgoryThmOriginal** [comment]
I'll try it, thank you! :-)
